# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arturo Fernandez - Software Engineer
email: 
description: > # this means to ignore newlines until "baseurl:"
  Arturo Fernandez personal website.
  Software Engineer and Technical book author.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: bsnux
github_username:  bsnux

# Build settings
markdown: kramdown
